#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。
[project]
id = "sevenc-nanashi.insert-aux2"
name = "insert.aux2"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[artifacts.English-insert-aul2]
destination = "English.insert.aul2"
source = "./i18n/English.insert.aul2"

[artifacts.insert-aux2]
destination = "Plugin/insert.aux2"

[artifacts.insert-aux2.profiles.debug]
build = "cargo build"
source = "target/debug/insert_aux2.dll"

[artifacts.insert-aux2.profiles.release]
build = "cargo build --release"
source = "target/release/insert_aux2.dll"

[release]
prebuild = ["cargo about generate ./about.hbs -o ./release/package.txt"]
package_template = "./release/package.txt"
package_information = "{name} v{version} / 「メディアを挿入」編集メニューを追加する汎用プラグイン"

[catalog]
id = "sevenc-nanashi.insert-aux2"
name = "insert.aux2"
summary = "「メディアを挿入」編集メニューを追加する汎用プラグイン"
author = "Nanashi."
type = "common"
description = { type = "url", url = "https://raw.githubusercontent.com/sevenc-nanashi/insert.aux2/main/README.md" }
download_source = { type = "github", owner = "sevenc-nanashi", repo = "insert.aux2" }
license = { type = "MIT", template = false, text = { type = "file", path = "./LICENSE" } }
homepage = "https://github.com/sevenc-nanashi/insert.aux2"
